apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: ameni
spec:
  containers:
  - name: container-db
    image: postgres
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "postgres"
