apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    app: res
spec:
  containers:
  - name: container-result
    image: kodekloud/examplevotingapp_result:v1
    ports:
    - containerPort: 80

